server:
    port: 8080

spring:
    profiles:
        active: prod
    data:
        mongodb:
            host: telosys-tools-saasdb
            port: 27017
            database: telosys-tools-saas


    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: true

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: telosys-tools-saas